### ISSUE TITLE
[SUGGESTION] U must likely known already.

### ISSUE THREAD

**Issue by notperry1234567890** [2D-Mesh-Plane/Python-Obfscation#3]
**Please describe your suggestion in detail.**
But incase u don't the rename function makes it go 大中國代碼可怕的黑客重命名功能。and not put : for the function so it breaks it ofc u can just add it there but still just pointing out.

**Additional context**
Add any other context or screenshots about the feature here.

**Comment by Madmegsox1** [comment]
Thanks for pointing that out i actually forgot about that bug :)
